Get url from props for prerender-data-provider
preactjs/preact-cli pull request #1446
Opened 2020-10-17 23:34 UTC by mattias-lonn

**What kind of change does this PR introduce?**
Bugfix

**Did you add tests for your changes?**
No

**Summary**
When example a query is included in the URL path, prerender-data-provider returns null as it doesn't check if the path exists without the query. Now it remaps the URL using given props matches.

**Does this PR introduce a breaking change?**
No

**Other information**
N/A

2020-10-30 18:11 UTC, prateekbh commented
or a test that would demonstrate the same

2020-10-30 21:07 UTC, mattias-lonn commented
@ForsakenHarmony: The idea is to ensure that the right json file is fetched by using the props.path instead of props.url. Using getUrlFromProps it will first define the url as props.path and then remap it using props.matches.

For example, if you go to http://localhost:8080/news/news-item-1/?sidebar=login without getUrlFromProps, the json data file path will be `/news/news-item-1/?sidebar=login/preact_prerender_data.json`. The problem is that the query is defined in the url and therefore it will fail to get the json data. This is why I'd remap props.url using props.matches, now the file path will be `/news/news-item-1/preact_prerender_data.json`

Sorry, I do not know how to setup jest for prerender-data-provider folder. @prateekbh, do you have any guidlines to setup a test for prerender-data-provider?
```
./preact-cli/packages/prerender-data-provider/src/hook.test.js
  3:1  error  'describe' is not defined  no-undef
```

2020-11-02 21:03 UTC, prateekbh commented on packages/prerender-data-provider/src/hook.js
> +	props.url = getUrlFromProps(props);
also there's an HOC

2020-11-02 21:50 UTC, prateekbh requested changes

2020-11-02 21:50 UTC, prateekbh commented on packages/prerender-data-provider/src/utils.js
> +	return url;
Ideally `normalizeUrl` should also strip query params

2023-02-08 10:01 UTC, closed without merging